on:
  push:
    branches:
      - "main"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Change to publish branch
        run: |
          git branch publish
          git checkout publish
      #
      # 実行用に各言語の環境をセットアップする
      #
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      #
      # 各言語のrun.shを実行しログを取得し移動させる
      #
      - name: Run scripts
        run: |
          mkdir outputs
          for lang in $(ls);
          do
            if [ -d $lang ];then
              mkdir ./outputs/$lang
              cd $lang;source run.sh
              mv *.log ../outputs/$lang/
              cd ..
              echo $lang >> ./outputs/langs.txt
            fi
          done

      #
      # HelloWorlds/publishへpushする
      #
      - name: Push to publish
        run: |
          git add .
          git commit -m "Auto generate"
          git push
