on:
  push:
    branches:
      - "main"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false
          cd $GITHUB_WORKSPACE
          ls
          cd $GITHUB_WORKSPACE
          git branch publish
          git fetch origin publish
          git checkout publish
          git checkout .
          git pull origin publish --rebase
          ls
      #
      # 実行用に各言語の環境をセットアップする
      #
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      #
      # 各言語のrun.shを実行しログを取得し移動させる
      #
      - name: Run scripts
        run: |
          cd $GITHUB_WORKSPACE/src
          for lang in $(ls);
          do
            if [ -d $lang ];then
              mkdir -p ../outputs/$lang
              cd $lang
              source run.sh >> ../../outputs/${lang}.txt
              mv *.log ../../outputs/$lang/
              cd ..
              echo $lang >> ../outputs/langs.txt
            fi
          done
          cd ..
      #
      # HelloWorlds/publishへpushする
      #
      - name: Push to publish
        run: |
          git add .
          git commit -m "Auto generate"
          git push --set-upstream origin publish
